### ISSUE TITLE
Type 2 : Can still push when stack reach its capacity

### ISSUE THREAD

**Issue by OngOngoing** [SSD2015/Stack#10]
```
    for(int i=0; i < stack.capacity(); i++) {
        stack.push("dummy");
    }
    String obj = new String("WTF");
    stack.push(obj);
    assertEquals(obj, stack.peek());
```

expected : assertEquals(obj, stack.peek()); return false
actual : assertEquals(obj, stack.peek()); return true

**Comment by jbrucker** [comment]
Good example but not complete.
What is "stack" and how was it created?
What if capacity is -1 (infinite stack)?
