### ISSUE TITLE
Type 1 return wrong element after pop

### ISSUE THREAD

**Issue by pNagi** [SSD2015/Stack#12]
```
Object item1 = new Integer(1);
stack.push(item1);
Object item2 = new String("Hello");
stack.push(item2);

stack.pop();
assertSame("should be the item1", item1, stack.peek());
```

expected value from pop: item2
actual value: item1

expected value from peek: item1
actual value: item2

**Comment by jbrucker** [comment]
Example is incomplete. It doesn't show what is "stack"
or how it was created.  What is the capacity of the stack?
