### ISSUE TITLE
Type 1: Stack size is error

### ISSUE THREAD

**Issue by runyasak** [SSD2015/Stack#13]
Stack size in type 1 will return the size in negative.

Code : 
Stack stack = StackFactory.makeStack(3);
assertEquals(3, stack.size());

Expected result : 3
Actual result : -3

**Comment by jbrucker** [comment]
You misinterpreting the Stack API.
size() is the number of items in the stack, not its capacity.
The expected result should be 0.
However, stack.size() is clearly returning an invalid value.
