### ISSUE TITLE
Type 1 stack.peek() return wrong Object

### ISSUE THREAD

**Issue by vincentvictor** [SSD2015/Stack#15]
```
public void testPeek(){
    Stack stack = getStack(1);
    assertNull( stack.peek() );
    Object item1 = new Double(1234);
    stack.push(item1);
    Object item2 = new String("Nichy");
    stack.push(item2);
    System.out.println(stack.peek().toString());
    assertSame(item2, stack.peek());
}
```

After push item2 and call method peek(), the program return value of item1.

**Comment by jbrucker** [comment]
Not a complete example.
This code doesn't show how Stack was created.
What is the capacity of this stack?
If capacity is 1, then 2nd call to push should fail.
Example should be complete and independent of JUnit,
so someone can reproduce it
