### ISSUE TITLE
Type 0 : Not throw RuntimeException after push more than capacity

### ISSUE THREAD

**Issue by TanDKY** [SSD2015/Stack#2]
When push the items, more than the stack's capacity, it will not throw the RuntimeException
Example Code : 

``` java
@Test ( expected = RuntimeException.class )
    public void testPushOntoFullStackStack(){ 
        stack.push(1);
        stack.push(1);
        stack.push(1);
        stack.push(1);
        stack.push(1);
        stack.push(1);
    }
```

It must pass because we already throw the exception, but it fails.

**Comment by jbrucker** [comment]
Good issue but example is not convincing.
Example does not show what "stack" is,
how it was created, or its capacity.

Example doesn't show _where_ you think exception
should be thrown.
